image: python:3
lint:
 stage: test
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --style google -i
 only:
 - merge_requests

 unittest:
 stage: test
 needs: 
 - pipeline: lint
   job: lint
 script:
 - pip install -r requirements.txt
 - pytest
 only:
 - merge_requests