image: python:3.11.0
lint:
 stage: build
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --style google --diff
 only:
 - pushes

unittest:
 stage: test
 dependencies:
 - lint
 script:
 - pip install -r requirements.txt
 - pytest
 only:
 - pushes

prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 dependencies:
 - lint
 - unittest
 environment: Production
 only:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - gcloud app deploy --quiet --project $PROJECT_ID