image: python:3
lint:
 stage: test
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --style google --diff
 only:
 - merge_requests

unittest:
 stage: test
 dependencies:
 - lint
 script:
 - pip install -r requirements.txt
 - pytest
 only:
 - merge_requests