image: python:3.11.0
lint:
 stage: build
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --style google --diff
 only:
 - merge_requests

unittest:
 stage: test
 needs: 
 - lint
 script:
 - pip install -r requirements.txt
 - pytest
 only:
 - merge_requests